package com.imaginamos.pruebaapps.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "APPLICATION".
 */
public class Application {

    private Long id;
    /** Not-null value. */
    private String name;
    private String urlImageSmall;
    private String urlImageMedium;
    private String urlImageLarge;
    private String summary;
    private Double price;
    private String currency;
    private String type;
    private String rights;
    private String title;
    private String link;
    private String idLabel;
    private String idNumber;
    private String bundleId;
    private String artist;
    private String artistLink;
    private String category;
    private String categoryId;
    private String scheme;
    private String releaseDate;

    public Application() {
    }

    public Application(Long id) {
        this.id = id;
    }

    public Application(Long id, String name, String urlImageSmall, String urlImageMedium, String urlImageLarge, String summary, Double price, String currency, String type, String rights, String title, String link, String idLabel, String idNumber, String bundleId, String artist, String artistLink, String category, String categoryId, String scheme, String releaseDate) {
        this.id = id;
        this.name = name;
        this.urlImageSmall = urlImageSmall;
        this.urlImageMedium = urlImageMedium;
        this.urlImageLarge = urlImageLarge;
        this.summary = summary;
        this.price = price;
        this.currency = currency;
        this.type = type;
        this.rights = rights;
        this.title = title;
        this.link = link;
        this.idLabel = idLabel;
        this.idNumber = idNumber;
        this.bundleId = bundleId;
        this.artist = artist;
        this.artistLink = artistLink;
        this.category = category;
        this.categoryId = categoryId;
        this.scheme = scheme;
        this.releaseDate = releaseDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public String getUrlImageSmall() {
        return urlImageSmall;
    }

    public void setUrlImageSmall(String urlImageSmall) {
        this.urlImageSmall = urlImageSmall;
    }

    public String getUrlImageMedium() {
        return urlImageMedium;
    }

    public void setUrlImageMedium(String urlImageMedium) {
        this.urlImageMedium = urlImageMedium;
    }

    public String getUrlImageLarge() {
        return urlImageLarge;
    }

    public void setUrlImageLarge(String urlImageLarge) {
        this.urlImageLarge = urlImageLarge;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getRights() {
        return rights;
    }

    public void setRights(String rights) {
        this.rights = rights;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public String getIdLabel() {
        return idLabel;
    }

    public void setIdLabel(String idLabel) {
        this.idLabel = idLabel;
    }

    public String getIdNumber() {
        return idNumber;
    }

    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber;
    }

    public String getBundleId() {
        return bundleId;
    }

    public void setBundleId(String bundleId) {
        this.bundleId = bundleId;
    }

    public String getArtist() {
        return artist;
    }

    public void setArtist(String artist) {
        this.artist = artist;
    }

    public String getArtistLink() {
        return artistLink;
    }

    public void setArtistLink(String artistLink) {
        this.artistLink = artistLink;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    public String getScheme() {
        return scheme;
    }

    public void setScheme(String scheme) {
        this.scheme = scheme;
    }

    public String getReleaseDate() {
        return releaseDate;
    }

    public void setReleaseDate(String releaseDate) {
        this.releaseDate = releaseDate;
    }

}
